### ISSUE TITLE
Mobs almost never spawn

### ISSUE THREAD

**Issue by nikijaz** [RelativityMC/VMP-fabric#11]
With VMP installed mobs almost never spawn.

**Comment by PhantomG27249** [comment]
can you provide more information? mod version, jvm, mod lists, fabric version, mc version etc. Example of mobs not spawning too.

**Comment by AViewFromTheTop** [comment]
I haven't been able to reproduce this, mobs spawn just fine for me.

**Comment by nikijaz** [comment]
Found the problem, it turns out it was not related to VMP.
