### ISSUE TITLE
Incompatibility with Create Fabric

### ISSUE THREAD

**Issue by ghost** [RelativityMC/VMP-fabric#14]
**Describe the bug**
Launching a modpack with both Create and VMP enabled causes a crash on startup.

**To Reproduce**
1. Launch a modpack with both Create and VMP enabled

**Runtime info (please complete the following information):**
 - OS: Windows 10
 - Minecraft version: 1.18.2
 - Mod version: Create mc1.18.2_v0.4.1+596, VMP 0.2.0+beta.3.17

**Crash reports / logs**
[https://pastebin.com/XXkhzqrH](https://pastebin.com/XXkhzqrH)

**Other mods**
(listed in log)

**Checklist**
 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

I'm also submitting this issue to the Create team since I don't know which is more likely to be able to fix the 'problem'.

**Comment by ishland** [comment]
The conflicting part: 

https://github.com/TropheusJ/serialization-hooks/blob/1.18/src/main/java/io/github/tropheusj/serialization_hooks/mixin/IngredientMixin.java#L48-L54

https://github.com/RelativityMC/VMP-fabric/blob/ver/1.18/src/main/java/com/ishland/vmp/mixins/general/ingredient_matching/MixinIngredient.java#L39-L59

VMP uses a completely different but more efficient method for ingredient matching and one of the dependencies of Create is modifying this part. The solution for Create is to use `@At("RETURN")` with cancellable injection as VMP is unlikely to get another beta release for 1.18.

**Comment by ishland** [comment]
Closing as the linked issue is closed.
