### ISSUE TITLE
CME in MixinChunkTicketManager#tickTickets when using with DimensionalThreading

### ISSUE THREAD

**Issue by skerit** [RelativityMC/VMP-fabric#17]
**Describe the bug**

A CME sometimes occurs when using VMP together with DimensionalThreading.

**Crash reports / logs**
https://pastebin.com/m72wcC0Y

**Checklist**
 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by skerit** [comment]
I'm going to see how many times this actually happens, because I've been running DimensionThreading for a while now, it doesn't come up often.

**Comment by ishland** [comment]
This issue should be fixed in 8b8ed5f86a. Can you try reproduce again?

**Comment by ishland** [comment]
Closing as resolved.
