### ISSUE TITLE
1.18.2 getting more up-to-date releases than 1.19

### ISSUE THREAD

**Issue by ghost** [RelativityMC/VMP-fabric#18]
**Describe the bug**
1.18.2 releases on Modrinth are published automaticially from Github (with literally every commit) while 1.19 releases are only published manually (only when a lot of changes pile up) leading to the 1.19 verison being massively outdated at times.

**Expected behavior**
 Either 1.19 versions being published automaticially too, or 1.18.2 backports not being published automaticially.

**Screenshots**

![unknown](https://user-images.githubusercontent.com/85982640/179204230-b0c48d35-08c6-4ae1-af93-0e8721e40ebe.png)

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by ishland** [comment]
Fixed. Builds for 1.19 will be automatically uploaded to modrinth.

**Comment by ghost** [comment]
> Fixed. Builds for 1.19 will be automatically uploaded to modrinth.

Wait, is it intended that the devbuilds are marked as alphas and their backports to 1.18.2 are marked as betas?

**Comment by ishland** [comment]
> > Fixed. Builds for 1.19 will be automatically uploaded to modrinth.
> 
> Wait, is it intended that the devbuilds are marked as alphas and their backports to 1.18.2 are marked as betas?

It is unintended but it is already published so I'm not changing it any more.
