### ISSUE TITLE
Incompatible with Carpet Fixes

### ISSUE THREAD

**Issue by nikijaz** [RelativityMC/VMP-fabric#19]
**Describe the bug**
Server crashes on startup with Carpet Fixes installed

**To Reproduce**
1. Install Carpet Fixes and VMP
2. Start the server

**Expected behavior**
Successful server startup

**Runtime info (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS x86_64
 - Minecraft version: 1.19
 - Mod version: 0.2.0+beta.6.21+1.19 (Just translated something into Russian, but it is not fixed in the original build)

**Crash reports / logs**
https://mclo.gs/gSpfXMD

**Other mods**
Carpet FIxes

**Checklist**
 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by nikijaz** [comment]
Could be related to https://github.com/fxmorin/carpet-fixes/issues/93

**Comment by FxMorin** [comment]
Can you test if this fixes the issue: https://github.com/fxmorin/carpet-fixes/suites/7441242650/artifacts/304265539

**Comment by nikijaz** [comment]
Fixed by the latest Carpet Fixes commits

**Comment by nikijaz** [comment]
Oops, now I have [this](https://mclo.gs/inNhb6d)

**Comment by FxMorin** [comment]
https://github.com/fxmorin/carpet-fixes/releases/tag/v1.11.0
