### ISSUE TITLE
Server crash and deadlock with Carpet Fixes

### ISSUE THREAD

**Issue by Tempest-5ky** [RelativityMC/VMP-fabric#20]
**Describe the bug**
More or less what it says on the box! Server crashes and deadlocks on startup, presumably because of a mixin conflict with Carpet-Fixes

**To Reproduce**
1. Install Carpet, Carpet-fixes, and Very Many Players on a server
2. Start server
3. Crash and deadlock, server is unable to stop itself properly and has to be force-stopped (killed)

**Expected behavior**
No crash, server starts normally and both mods work as intended

**Screenshots**

**Runtime info (please complete the following information):**
 - OS: Linux
 - Minecraft version: 1.18.2
 - Mod version: 1.2.0+beta.3.68
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**
Server did not generate a crashlog due the deadlocked state, but here's what was in the latest.log when it happened: https://mclo.gs/oavKH2T

**Other mods**
A truly ungodly amount, but I managed to narrow it down to carpet fixes being the issue

**Checklist**

 - [X] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. 
 - [X] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by nikijaz** [comment]
@Tempest-5ky 
It is fixed in the latest Carpet-Fixes version (v1.11.0)

**Comment by Tempest-5ky** [comment]
Ahh unfortunately that version is 1.19 so it's not useful for me, but seeing as it's an issue with that mod and not this one i'll close the issue!
