### ISSUE TITLE
[INCOMPATIBILITY] v0.2.0+beta.3.73 and higher completely breaks Pehkui

### ISSUE THREAD

**Issue by Tempest-5ky** [RelativityMC/VMP-fabric#21]
**Describe the bug**
As of its v0.2.0+beta.3.73 1.18.2 release, VMP completely breaks Pehkui (https://www.curseforge.com/minecraft/mc-mods/pehkui). Neither generate any log errors, but when loaded together, Pehkui cannot modify the scales of players (and presumably any entity, though i'll admit I didn't think to test that). 
The /scale command will execute, and using "/scale get" will indicate that the scale _has_ been modified, but it obviously hasn't, as the jump height, entity scale, reach, or **any other scale type** will not change. Downgrading VMP to v0.2.0+beta.3.69 or lower gets rid of the issue. 

This bug also affects any mod that relies on Pehkui for its entity scaling, such as Origins and CPM.

**To Reproduce**
1. Load v0.2.0+beta.3.73 or higher of VMP alongside Pehkui
2. Try to modify any scale using /scale

**Expected behavior**
The two mods working normally alongside each other

**Screenshots**

n/a

**Runtime info (please complete the following information):**
 - OS: Linux
 - Minecraft version: 1.18.2
 - Mod version: 
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**

n/a

**Other mods**

None, besides the mods' respective dependencies

**Checklist**

 - [x ] I am using the official version of the mod. 
 - [x ] I tried the latest development version but the issue persists. 
 - [x ] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by Tempest-5ky** [comment]
Update: possible fix on pehkui's end?
https://github.com/Virtuoel/Pehkui/issues/305#issuecomment-1200514708

**Comment by ishland** [comment]
Closing as resolved since pehkui will have a fix in their next release: Virtuoel/Pehkui#305

Feel free to open a new ticket if it happens again with their next release.
