### ISSUE TITLE
1.19.2 crash: NoSuchFieldError

### ISSUE THREAD

**Issue by PoneyClairDeLune** [RelativityMC/VMP-fabric#22]
**Describe the bug**

**To Reproduce**
1. Install VMP
2. Launch Minecraft
3. Minecraft crashes upon only showing a window

**Expected behavior**
Minecraft crashes with NoSuchFieldError. [Pastebin](https://pastebin.com/gSvW5ZD9)

**Screenshots**
N/A

**Runtime info (please complete the following information):**
(Available in the crash log)

**Crash reports / logs**
[Crash](https://pastebin.com/gSvW5ZD9)

**Other mods**
(Available in the crash log)

**Checklist**

 - [x] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**
N/A

**Comment by ishland** [comment]
Release builds don't support 1.19.2 yet. Please try reproduce with [this version](https://modrinth.com/mod/vmp-fabric/version/0.2.0%2Bbeta.6.47%2B1.19.2).

**Comment by PoneyClairDeLune** [comment]
Issue doesn't exist in the provided development version.
