### ISSUE TITLE
Slow teleport with WWOO

### ISSUE THREAD

**Issue by clmc99** [RelativityMC/VMP-fabric#24]
**Describe the bug**
Teleporting takes a while with both VMP and William Wythers' Overhauled Overworld loaded.

**To Reproduce**
1. Put the latest 1.19.2 versions of VMP, WWOO, and Fabric API in your mods folder.
2. Open Minecraft and make a new world.
3. Try to teleport somewhere (I used 1000, 100, 1000 when I was binary searching through my modlist, but I also tried 2000, 100, 2000 once and got the same result). The world will not freeze, but the teleport command may take up to 30 seconds to register.

**Expected behavior**
Teleport command registers quickly; player teleports

**Screenshots**

**Runtime info (please complete the following information):**
 - OS: Windows 11
 - Minecraft version: 1.19.2
 - Mod version: vmp-fabric-mc1.19.2-0.2.0+beta.7.0-all.jar
 - CPU: Intel i7-9750HF @2.60GHz
 - GPU: Nvidia GeForce 1660 Ti
 - RAM: 16 GB

**Other mods**
WWOO
Fabric API

**Checklist**
 - [x ] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. _I used the latest release—is there a specific dev version I should download or compile somewhere?_
 - [x ] I searched for similar open issues and could not find an existing bug report on this.

**Comment by ishland** [comment]
This is an actual feature in vmp that does lag-free teleports. This usually indicates that your system cannot handle the worldgen datapack.

**Comment by ishland** [comment]
Closing as resolved.
