### ISSUE TITLE
Extreme lag spikes when crossing chunk borders

### ISSUE THREAD

**Issue by tyrannus00** [RelativityMC/VMP-fabric#28]
**Describe the bug**
With VMP installed the internal server (in singleplayer) freezes for 800 - 1000ms when crossing chunk borders.

**To Reproduce**
1. Cross a chunk border
2. Feel the lag

**Expected behavior**
No Lag when crossing chunk borders.

**Runtime info (please complete the following information):**
 - OS: Windows 10
 - Minecraft version: 1.19.2
 - Mod version: 0.2.0 beta.7.5
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**
Nothing in the logs hints at the lag.

**Other mods**
https://pastebin.com/AsU097k2

**Checklist**

 - [x ] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. 
 - [x ] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**
I am experiencing this bug on a map called greenfield ( a massive city). I am sure it is this mod, because I removed a lot of mods 1 at a time and only after removing VMP the issue stopped happening.

**Comment by ishland** [comment]
Install [spark](https://spark.lucko.me/) and try this: https://spark.lucko.me/docs/guides/Finding-lag-spikes

**Comment by ishland** [comment]
Closing as stale.
