### ISSUE TITLE
Abnormal Behavior when breaking/interacting with blocks on dedicated server (1.19.2)

### ISSUE THREAD

**Issue by Funtimes909** [RelativityMC/VMP-fabric#29]
**Describe the bug**
interacting/breaking blocks on a dedicated linux server does not apply changes until logging in again/restarting the server

**To Reproduce**
1. Start a server using latest developmental release of VMP (vmp-fabric-mc1.19.2-0.2.0+beta.7.11-all)
2. Log in and try to break/interact with blocks

**Expected behavior**
I expected that breaking blocks would act like normal

**Screenshots**

https://user-images.githubusercontent.com/68979259/198191467-5fb9fe8a-ee4b-4bd3-9c66-bff583522c22.mp4

**Runtime info (please complete the following information):**
 - OS: Debian Linux with KDE Plasma, kernel version 6.0.0-2-amd64 for both
 - Minecraft version: 1.19.2
 - Mod version: vmp-fabric-mc1.19.2-0.2.0+beta.7.11-al
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**
https://mclo.gs/lWurNuP (Client Log)
[latest.log](https://github.com/RelativityMC/VMP-fabric/files/9875724/latest.log) (Server Log)

**Other mods**

![image](https://user-images.githubusercontent.com/68979259/198190173-93a5818f-1c49-4aa4-8572-a5f41c454845.png)
Server Mods List

![image](https://user-images.githubusercontent.com/68979259/198190441-f09e5ce0-72f8-49dc-bcdd-aa74827a175e.png)
Client Mod List

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

![image](https://user-images.githubusercontent.com/68979259/198189998-9cfd059c-ec61-4986-98ef-1fb15aaea75b.png)
Server Specs

![image](https://user-images.githubusercontent.com/68979259/198190046-74f98189-208a-48cf-a4c4-f035c3d43b30.png)
Client Specs

**Comment by ishland** [comment]
I would suspect it is a mod compatibility issue. Try reproduce with only vmp. If things work with only vmp then try get the minimum set of mods that's reproducible.

**Comment by ishland** [comment]
Closing as stale.
