### ISSUE TITLE
Extreme Lag Spike on chunk loading and chunks are slowly rendered

### ISSUE THREAD

**Issue by SteveKunG** [RelativityMC/VMP-fabric#30]
**Describe the bug**
When flying around the map, Lag spikes occurred on chunk loading. And chunks sometime are slowly rendered. Probably same as #28

**To Reproduce**
1. Flying around the map
2. Press Alt + F3 to see the lag spikes (If using ServerTick mod)

**Expected behavior**
Chunk loading shouldn't causes the lag.

**Screenshots**
![2022-10-30_13 14 07](https://user-images.githubusercontent.com/6128413/198868215-eb8375ab-ecd6-4d02-8145-c2018d6b22ef.png)

**Runtime info (please complete the following information):**
 - OS: Windows 10
 - Minecraft version: 1.19.2
 - Mod version: vmp-fabric-mc1.19.2-0.2.0+beta.7.11-all
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**
https://spark.lucko.me/sssjGLpCue

**Other mods**
![image](https://user-images.githubusercontent.com/6128413/198868370-99f6c6ee-1f7d-4b57-aedc-ddcd45b467d5.png)

**Checklist**

 - [x] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. 
 - [ ] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by ishland** [comment]
Try reproduce without vmp.

**Comment by SteveKunG** [comment]
Here is a profiler without VMP. Chunks are loading much faster and less lag spikes if VMP is not installed.
https://spark.lucko.me/HH4RpKxLSH

![2022-10-30_18 33 31](https://user-images.githubusercontent.com/6128413/198876312-f316a651-ecda-4be3-b9a9-9d1047691f32.png)

**Comment by ishland** [comment]
Try disabling `precache_biome_lookup` in `vmp.properties`

**Comment by SteveKunG** [comment]
It seems good so far, with some lag spikes but that's fine.
https://spark.lucko.me/fWzqf2FbkV

![2022-11-10_23 13 25](https://user-images.githubusercontent.com/6128413/201148420-4769a275-d86d-49da-8da4-97a5d2a89525.png)

**Comment by SteveKunG** [comment]
Do you need more testing from https://github.com/RelativityMC/VMP-fabric/commit/cf9eafaa577602fb20ae04332990f377cd15cf59?

**Comment by ishland** [comment]
> Do you need more testing from [cf9eafa](https://github.com/RelativityMC/VMP-fabric/commit/cf9eafaa577602fb20ae04332990f377cd15cf59) ?

Yes if you have enough time to do that.

**Comment by SteveKunG** [comment]
Here it is, all good so far. Maybe closing this?
https://spark.lucko.me/49bqgZGWv7

![2023-01-26_13 22 29](https://user-images.githubusercontent.com/6128413/214770890-31fd758c-f6c8-44f0-b70b-3612ed493b7b.png)

**Comment by ishland** [comment]
Closing as resolved.
