### ISSUE TITLE
Adorn incompatible 

### ISSUE THREAD

**Issue by lostopkk** [RelativityMC/VMP-fabric#33]
**Describe the bug**
Adorn with VMP is bugged

everything about that is in this issue: https://github.com/Juuxel/Adorn/issues/287

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by ZekeZDev** [comment]
It looks like with 1.20.1 this issue is happening again with this error:
"[16:02:22] [Render thread/WARN]: Received passengers for unknown entity"
