### ISSUE TITLE
Instant disconnects on 1.19.2

### ISSUE THREAD

**Issue by ahribellah** [RelativityMC/VMP-fabric#34]
**Describe the bug**
All players on the server instantly disconnect a random number of times before the server lets them in when the mod is installed.

**To Reproduce**
1. Install the mod on 1.19.2 (Fabric version 0.14.12)
2. Attempt to connect.

**Expected behavior**
Players connect to the server without issue.

**Screenshots**
N/A

**Runtime info (please complete the following information):**
 - OS: Windows 10
 - Minecraft version: 1.19.2
 - Mod version: 0.2.0+beta.7.15 (came with Dreamcraft Fabric 1.19.2)
 - Mod branch: no idea

**Crash reports / logs**
Disconnected

**Other mods**
Dreamcraft Fabric 1.19.2: https://www.curseforge.com/minecraft/modpacks/dreamcraft-new

**Checklist**

 - [ ] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**
Removing the mod instantly fixed the problem.

I think 0.2.0+beta.7.23 is the latest version? I can give that a shot, but I don't really need the mod on my server, as it's a small server. I am submitting this report primarily because it was included in a modpack I'm using and caused obscure issues.

**Comment by ahribellah** [comment]
Sorry, I see that this is a duplicate of https://github.com/RelativityMC/VMP-fabric/issues/31. It's been a long morning.

**Comment by ishland** [comment]
That workaround should no longer be needed with newer versions (starting from `0.2.0+beta.7.17`).  Please retest with the current devbuild.

**Comment by ahribellah** [comment]
0.2.0+beta7.23 works without the workaround, though I did also change the setting mentioned in https://github.com/RelativityMC/VMP-fabric/issues/32#issuecomment-1358249051 to make sure there wasn't lag with blocks breaking.
