### ISSUE TITLE
Connection lost when joining server sometimes

### ISSUE THREAD

**Issue by HySand** [RelativityMC/VMP-fabric#35]
**Describe the bug**
Failed to join server sometimes

**To Reproduce**
1. Join server
2. See error

**Screenshots**

**Runtime info (please complete the following information):**
 - OS: Linux
 - Minecraft version: 1.19.2
 - Mod version: 0.2.0 beta7

**Crash reports / logs**
https://pastebin.com/1rHkiD2w

**Other mods**
https://pastebin.com/w2SxXpQq

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by ishland** [comment]
The mod list is invalid and it seems that you did not try the latest dev build. 
Try reproduce with latest devbuild.

**Comment by HySand** [comment]
My bad. I updated mod list url and VMP to build beta7.23, everything works untill server crash (May be caused by Better Nether, server crash everytime a player join server, fixed by deleting DIM-1 files), server can't be started again untill removing VMP.
Crash report https://pastebin.com/vDY80qMJ
Latest.log https://pastebin.com/cLaVanVT

**Comment by ishland** [comment]
Try disabling the experimental optimize chunk iteration in vmp config since servercore also have this feature.

**Comment by HySand** [comment]
It works perfectly now. Thank you and your mod!
