### ISSUE TITLE
Sometimes some chunks don't load

### ISSUE THREAD

**Issue by Soochaehwa** [RelativityMC/VMP-fabric#4]
![2021-12-19_23 00 32](https://user-images.githubusercontent.com/43947445/146678011-a592e7df-a78d-43cb-a485-1a13d46801cb.png)
![2021-12-19_23 00 03](https://user-images.githubusercontent.com/43947445/146678016-72bcd030-d3fc-4272-8b65-6f971918344c.png)
![2021-12-19_23 00 13](https://user-images.githubusercontent.com/43947445/146678017-c0fffee3-2224-4bc7-9888-a31b969ccead.png)
![2021-12-19_23 00 23](https://user-images.githubusercontent.com/43947445/146678018-2007b901-41de-4710-9c6e-946b8b169542.png)
![2021-12-20_01 06 39](https://user-images.githubusercontent.com/43947445/146682222-8d9f340e-90af-41ac-8395-6ecc22bdd3ee.png)
![2021-12-20_01 36 15](https://user-images.githubusercontent.com/43947445/146683014-71947aeb-3150-4a55-ae70-b57ba3cd41b9.png)

Sometimes some chunks don't load

https://ibb.co/tqMcts0
https://ibb.co/2S3tBGD
This is a screenshot sent by a player on my server 

I updated C2ME and added VMP today
At first I thought it was a C2ME problem, so I deleted C2ME and tested it, but it was the same. 

```
alternate-current-mc1.18-1.1.0.jar
apples-carrots-1.5.jar
architectury-3.2.51.jar
bedbenefitsfabric-1.18-0.1.0.jar
betterleads-1.0.1+1.18.1.jar
bettersafebed-1.18-fabric-a.jar
bfapi.jar
c2me-fabric-mc1.18.1-0.2.0+alpha.5.106-all.jar
carpet-tis-addition-mc1.18.1-v1.27.2.jar
chestrefill-1.0.2-fabric.jar
Chunky-1.2.153.jar
cloth-config-6.0.42-fabric.jar
commandspy-1.2.4.jar
connected-doors-1.1+1.18.jar
EditSign-1.18-2.2.6.jar
fabric-api-0.44.0+1.18.jar
fabric-carpet-1.18-1.4.56+v211130.jar
fabric-enchantments-0.6.1.jar
fabric-language-kotlin-1.7.0+kotlin.1.6.0.jar
fabrication-1.18-2.3.0.jar
FabricPvP-0.1.0.jar
FabricSit-1.7.1.jar
FallingTree-1.18-2.15.0.jar
farmers-delight-fabric-1.18.1-0.2.0.jar
ferritecore-4.0.0-fabric.jar
graves-1.2.2+1.18.jar
headindex-1.0.4.jar
htm-1.1.4.jar
InventorySorter-1.8.1-1.18.jar
InvView-1.4.8-1.18+.jar
krypton-0.1.6.jar
kubejs-fabric-1801.4.0-build.245.jar
lapisreserve-1.0.8.jar
lazydfu-0.1.2.jar
ledger-1.2.0.jar
lithium-fabric-mc1.18.1-0.7.6.jar
LuckPerms-Fabric-5.3.86.jar
notenoughcrashes-4.1.3+1.18-fabric.jar
player-events-2.2.2.jar
polymc-3.3.2+1.18.1.jar
quartz-elevator-2.0.0+1.18.jar
recipecache-0.2.1-1.17.1.jar
rhino-fabric-1800.1.6-build.81.jar
rightclickharvest-1.5.1.jar
rpgstats-4.3.1+1.18.1.jar
semblance-1.1.0.jar
server-hats-0.8.jar
servercore-1.2.6-1.18.1.jar
ServerPropertiesReload-Fabric-1.18+v1.0.3.jar
spark-fabric.jar
starlight-1.0.0+fabric.d0a3220.jar
styled-chat-1.2.2+1.18.jar
styledplayerlist-2.1.3+1.18.jar
textile_backup-2.3.0-1.18.jar
vmp-fabric-mc1.18.1-0.2.0+beta.2.0-all.jar
wires-1.0.5.jar
```
This is the mod list

**Comment by ishland** [comment]
Should be fixed by 178702d
