### ISSUE TITLE
Emotes not rendering with Essential Mod

### ISSUE THREAD

**Issue by wlej** [RelativityMC/VMP-fabric#41]
**Describe the bug**
Cosmetics not rendering with Essential Mod

**To Reproduce**
1. Open the Emote wheel in Essential
2. See error

**Expected behavior**

**Screenshots**

**Runtime info (please complete the following information):**
 - OS: Windows 11
 - Minecraft version: 1.19.2
 - Mod version: 0.2.0
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**

**Other mods**

**Checklist**

 - [x ] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. 
 - [ x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by ishland** [comment]
`0.2.0` is not a valid version.
