### ISSUE TITLE
Elytra and trident hover endlessly and the character can't get back on his feet

### ISSUE THREAD

**Issue by PegasovFly** [RelativityMC/VMP-fabric#44]
Hello, while playing with this mod, elites and trident behave strangely when there is 1 person online on the server, there are no problems, but when 2 players are on the server and they do not touch chunks, then when you land, you hang up and can't get up, help t re-entry, but when someone to it suits you, and this is another player, then you instantly get up.

After I removed this mod, this problem was no longer observed

 - Linux Ubuntu 22.04.2 LTS
 - Fabric 1.19.4
 - 0.2.0+beta.7.71 devbuild for 1.19.4
   - Very Many Players (Fabric)
 
 

https://user-images.githubusercontent.com/69050165/236034799-5b9ec1ca-3b48-4093-a2a8-cfd57a283aa7.MOV

 
![Безымянный1](https://user-images.githubusercontent.com/69050165/236034691-127efafe-a7ad-4f85-a6f0-b8c70c4437fb.png)

![Безымянный2](https://user-images.githubusercontent.com/69050165/236034715-9d74e493-1d20-4ce8-bac6-db764056b489.png)

![Безымянный3](https://user-images.githubusercontent.com/69050165/236034726-f12f5ed7-5d31-4362-81e4-ad5e79146be6.png)

Checklist

- [x] I am using the official version of the mod.

- [x] #45

- [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by Howie0715** [comment]
This bug seems to have appeared again in the latest version.

**Comment by ishland** [comment]
> This bug seems to have appeared again in the latest version.

Cannot reproduce on 1.20.4 with `0.2.0+beta.7.135` in a LAN world. Please try reproduce with only vmp.
