### ISSUE TITLE
Please add VMP - Forge 1.19.2-1.19.4

### ISSUE THREAD

**Issue by MrJorman** [RelativityMC/VMP-fabric#46]
ServerCore mod released on Forge 1.19.2

Your wonderful mod is very much needed on Forge, please make a port, it is very necessary! Since there are more main mods on Forge, and Fabric is empty right now.

**Comment by GitJhopa** [comment]
Forge?

**Comment by TheBossMagnus** [comment]
https://modrinth.com/mod/vmp-forge
