### ISSUE TITLE
This is Shit Bruh 0 TPS

### ISSUE THREAD

**Issue by DonorKrovi** [RelativityMC/VMP-fabric#51]
https://spark.lucko.me/SpluafiJ2c

**Comment by TheBossMagnus** [comment]
Ignoring the fact that you are doing 16 avg tps (not 0), the issue is that you have a ton of entities called "area_effect_cloud". 
![image](https://github.com/RelativityMC/VMP-fabric/assets/92474350/4edf2087-6db0-4e7e-a0a5-723051cb817c) 
Idk wich mod could cause this, but most likely it's not vmp.

**Comment by toinouH** [comment]
The issue template has not been filled properly and it does not help us to understand the situation.
Please fill the issue template :)
