### ISSUE TITLE
Disconnecting from the game while riding a horse corrupts the world

### ISSUE THREAD

**Issue by deb0ch** [RelativityMC/VMP-fabric#52]
**Describe the bug**
Disconnecting from the game while riding a horse corrupts the world. Reproduced on a clean install of the game, adding VMP as the only mod, or resource pack. I had to go through my ~92 mods to isolate this one 😅 Thank you teacher from middle school who taught me dichotomy 🙏 

Creating a new world and pasting the ` region` folder in it "fixes" the world.

In its broken state, you cannot break or place blocks, or sometimes it happens after a large delay. Mobs also get frozen in place, they still look at you and turn around but do not move. From time to time they get unstuck. You cannot pickup items either. Once my horse even came back under me after a few minutes !

This behavior makes me think of the hard drive becoming inaccessible to the game for anything that it is trying to do that would need writing to the disk, like placing or breaking blocks, mob positions, entities... It behaves as if there was a sort of DDoS attack on hard drive writes from the game, like something flooding disk access, since it _sometimes_ succeeds after a delay where normally it would be instantaneous.

This bug happened in single player.

**To Reproduce**
1. Log into the game
2. Mount a horse
3. Disconnect

When you log back in, your horse is not under you anymore and the world is broken as described above.

**Expected behavior**
World does not get corrupted.

**Screenshots**
Screen recording:
- 1 world load to get on a horse
- Disconnected
- Logged back in (2nd world load in the log)
- World broken

My GPU is struggling with resolution changes, hence the blinking for ~1min at game launch. Then framerate is really hurt when I switch to windowed mode with the 4k resolution of my screen, but this is unrelated to the bug.

https://www.loom.com/share/69247cc1091a4e1fbe14d939f756afa0?sid=85311854-526d-4eb6-8aca-bde962443d2a

**Runtime info (please complete the following information):**
 - OS: Windows 11
 - Minecraft version: 1.20.2
 - Mod version: 0.2.0+beta.7.121+1.20.2
 - Mod branch: N/A

**Crash reports / logs**
https://mclo.gs/4vHVotH 

**Other mods**
No other mods

**Checklist**
 - [x] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. _I already spent enough time reproducing on the latest release._
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**
I made a Modrinth modpack with the clean install and an uncorrupted version of the world I used in the video :

https://drive.google.com/file/d/1doX1hPNRuNyEdc0W8go6SGxfMCZ13DwH/

**Comment by ishland** [comment]
This is a known issue. Pressing shift should resolve this.

**Comment by deb0ch** [comment]
> This is a known issue. Pressing shift should resolve this. 

WTF is this thing not advertised with blinking letters 😳
