### ISSUE TITLE
Memory Leak Fix & VMP conflict on 1.20.1 fabric

### ISSUE THREAD

**Issue by neinwhal** [RelativityMC/VMP-fabric#57]
**Describe the bug**
Game in 1.20.1 crashes with only both the latest memory leak fix mod (1.1.4) + VMP (0.2.0+beta.7.102) and the associated fabric apis.

**To Reproduce**
1. Get fabric 1.20.1 loader and apis
2. Get memory leak fix + very many players

**Runtime info (please complete the following information):**
 - OS: windows
 - Minecraft version: 1.20.1 
 - Mod version: 0.20+beta.7.102

**Crash reports / logs**
https://pastebin.com/raw/F8X1SYaV

**Checklist**
 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**
This seems to only occur after the recent updates in memory leak fix, it occurs with both 1.1.4 and 1.1.3 of memory leak fix, but 1.1.2 works fine. Because the logs outputs an error from vmp, i thought to report here, but its a memory leak fix issue, lmk, and ill start one up there too.

**Comment by ishland** [comment]
It seems that you are trying to run a 1.17 version of memoryleakfix on 1.20.1.

**Comment by neinwhal** [comment]
memory leak fix has always been labelled as 1.17+?

![image](https://github.com/RelativityMC/VMP-fabric/assets/3191240/f2d9cf1a-10a5-4394-b863-fd48a5f5558a)

And the version is supported as so on modrinth.

**Comment by neinwhal** [comment]
^ For version 1.1.3 it's clearly stated to support 1.20.x as well, and that still results a crash.
The only compatible version as of now is 1.1.2.

**Comment by ishland** [comment]
From the error it is clearly a version mismatch. But please try reproduce without VMP.

**Comment by neinwhal** [comment]
Memory fix leak 1.1.4 seems to be working fine though without VMP, even with other mods and various other major optimization mods.
This might be more of an issue from memory fix leak's side conflicting with you then? If so ill redirect the report there.

**Comment by neinwhal** [comment]
Ok yeah, confirmed, sometimes it crashes on *loading world with memory fix leak 1.1.4.
Thanks, will redirect there.
