### ISSUE TITLE
Carpet mod fake player doesnt appear with use_async_chunks_on_login=true

### ISSUE THREAD

**Issue by juls0730** [RelativityMC/VMP-fabric#58]
**Describe the bug**
When spawning carpet mod fake players, for example `/player Alex spawn` in the console logs, it says that Alex joined the game, then VMP says "Async chunk loading for player Alex completed", and the Alex fake player appears in the tab menu, however, the fake player does not appear.

**To Reproduce**
1. Install carpet mod and optionally apply [this patch](https://github.com/gnembon/fabric-carpet/pull/1849) or [download the patched version](https://www.dropbox.com/scl/fi/fvr9tkntsiaua60punybs/fabric-carpet-1.20.3-1.4.128-v240311.jar?rlkey=qdpm2qpb8l9ouz6q31d4z1tid&dl=0) from my Dropbox if you trust a random stranger on the internet. I have this patch applied in order to get C2ME to work with carpet fake players, I don't think it affect the VMP issue, but just an important note
2. `/player Alex spawn`
3. Alex joined the game, but does not exist

**Expected behavior**
Alex should join the game and act like a normal player, you can see the expected behavior if you set use_async_chunks_on_login to false in the vmp.properties 

**Screenshots**
N/A

**Runtime info (please complete the following information):**
 - OS: Linux
 - Minecraft version: 1.20.4
 - Mod version: 0.2.0+beta.7.138 devbuild for 1.20.4
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**
No crash or logs reported

**Other mods**
Carpet mod

**Checklist**

 - [X] I am using the official version of the mod. 
 - [X] I tried the latest development version but the issue persists. 
 - [X] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**
I believe #39 is the same issue

**Comment by ishland** [comment]
There is obviously some warnings when this is happening: 
```
[Server thread/INFO] (Minecraft) Alex[local] logged in with entity id 813 at (20.975955376011925, 63.0, 16.650653411210776)
[Server thread/INFO] (Minecraft) Alex joined the game
[Server thread/INFO] (Minecraft) Async chunk loading for player Alex completed
[Render thread/INFO] (Minecraft) [System] [CHAT] Alex joined the game
[Render thread/WARN] (Minecraft) Server attempted to add player prior to sending player info (Player id ec561538-f3fd-461d-aff5-086b22154bce)
[Render thread/WARN] (Minecraft) Skipping Entity with id entity.minecraft.player
```
Not providing any logs lowers the priority of this issue. Anyways, a fix is on the way.

**Comment by juls0730** [comment]
Thank you. I apologize for missing warnings in the logs, and not providing any in the first place.
