### ISSUE TITLE
Immersive Portal entity rendering incompabilities

### ISSUE THREAD

**Issue by Senjosei** [RelativityMC/VMP-fabric#59]
**Describe the bug**
Regardless if there's a portal or not, when its loaded with immersive portals, in certain conditions, entities (block entities too) may not render, when the config option `use_optimized_entity_tracking` is set to true. Setting it to false fixes the issue

**To Reproduce**
1. Get on a super flat world with the config option `use_optimized_entity_tracking` set to true 
2. Create a 4 block high pillar
3. Stand on the ground and place a sand block on the side of the pillar
4. Observe the invisible sand block entitiy lol. (If the falling block entity is still visible, try various heights and camera angle when placing the sand.)

**Expected behavior**
The falling block entity to be visible the whole way down.

**Runtime info (please complete the following information):**
 - OS: Windows 11
 - Minecraft version: 1.20.1
 - Mod version: 0.2.0+beta.7.102

**Crash reports / logs**
No errors on logs

**Other mods**
(Minimal reproducible)
- Fabric API
- Immersive Portals
- Iris
- Sodium
- VMP

**Checklist**

 - [x] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by ishland** [comment]
From brief investigation immersive portals and VMP's entity tracking optimization are both attempting to manage entity trackers and these management doesn't co-exist. You'll have to disable one of them. 

VMP's entity tracking optimization assumes that only nearby entities are visible to players.
