### ISSUE TITLE
Adorn Incompatability causing Visual Glitches on Couches

### ISSUE THREAD

**Issue by MaskedElephant** [RelativityMC/VMP-fabric#60]
**Describe the bug**
With the Adorn mod and the most recent version of VMP, there is a visual glitch on servers where players become stuck to couches.
**To Reproduce**
1. Have both the Adorn mod and the most recent version of VMP installed on a 1.19.2 Fabric server and have multiple sit in chairs
2. Players become visually stuck and glitch out, and the glitch only ends upon relogging

**Expected behavior**

**Screenshots**

**Runtime info (please complete the following information):**
 - OS: Windows
 - Minecraft version: 1.19.2
 - Mod version: 0.2.0+beta.7.0 for 1.19.2

**Crash reports / logs**

**Other mods**

**Checklist**

 - [x ] I am using the official version of the mod. 
 - [x ] I tried the latest development version but the issue persists. 
 - [x ] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by MaskedElephant** [comment]
Also, I know there was a similar closed issue from November of 2022 where it was said it had been fixed, but it doesn't seem like it has.

**Comment by ishland** [comment]
`0.2.0+beta.7.0` is obviously not the current latest version (`0.2.0+beta.7.30` for 1.19.2). Please try reproduce with that version instead.

**Comment by MaskedElephant** [comment]
Sorry, I should rephrase, I am using that version, which I believe is the latest version *for 1.19.2*, which is having issues.I apologize for the miscommunication.

**Comment by ishland** [comment]
I'm unable to reproduce this issue with Adorn `3.9.1+1.19.2`, VMP `0.2.0+beta.7.30`. Chairs and Sofas seem to work just fine for me.
