### ISSUE TITLE
Server replay incompatibility

### ISSUE THREAD

**Issue by DOKIomen** [RelativityMC/VMP-fabric#65]
**Describe the bug**

**To Reproduce**
1. Do something
2. See error

**Expected behavior**

**Screenshots**

**Runtime info (please complete the following information):**
 - OS: 
 - Minecraft version: 
 - Mod version: 
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**

**Other mods**

**Checklist**

 - [ ] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. 
 - [ ] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by ishland** [comment]
Please fill the issue template.
