### ISSUE TITLE
Can't be fully compatible with carpet mod

### ISSUE THREAD

**Issue by HongyiHank** [RelativityMC/VMP-fabric#67]
Minecraft version:1.21(fabric-server-mc.1.21-loader.0.15.11-launcher.1.0.1)
Mod version:0.2.0+beta.7.162 devbuild for 1.21

When I spawn a fakeplayer above the bedrock in The Nether, the fakeplayer disappears, but "tab" lists the player's ID (this only happens when spawning a fakeplayer above the bedrock, not anywhere else).

**Comment by ishland** [comment]
Please fill the issue template. Also try reproduce without VMP.
