### ISSUE TITLE
与模组"[YSM]是，史蒂夫模型"存在兼容性问题

### ISSUE THREAD

**Issue by stoneStarRiver** [RelativityMC/VMP-fabric#71]
在与"YSM"同时加载时"YSM"模组会出现模型错位
测试时使用了游戏版本1.19.2和1.21Fabric，模组YSM最新版2.2.1和VMP最新版本，可以稳定复现
(测试时只添加了这两个模组,视频里不是)
https://github.com/user-attachments/assets/cc58ba9b-95b9-4d56-918c-da65744d157a
我不确定VMP是否应该与YSM模组兼容 所以我会在YSM模组的MCMOD页面编辑提示此问题

**Comment by ishland** [comment]
Please fill the issue template.

**Comment by stoneStarRiver** [comment]
**Describe the bug**
与模组"YSM"同时加载时模组"YSM"会出现模型错位

**To Reproduce**
Steps to reproduce the behavior:
1. 打开"YSM"GUI界面后点击右上角打开配置界面后退出进行下蹲 奔跑 走路等动作
2. "YSM"模型出现错位

**Expected behavior**
希望可以兼容模组"YSM"

**Screenshots**
https://github.com/user-attachments/assets/80df12a3-13bb-432a-ae51-28278a70f0fb

**Runtime info (please complete the following information):**
 - OS: Windows 11
 - Minecraft version: 1.21
 - Mod version: 0.2.0+beta.7.163

**Crash reports / logs**
https://paste.ubuntu.com/p/j2fg6P7Y5G/

**Other mods**
使用其他模组情况一样,只使用"VMP"和"YSM"也是一样

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**
我在单人世界测试了1.19.2和1.21,一百多个模组与只有"YSM"和"VMP"这两个模组结果是完全一样的,排除了与其他模组不兼容的可能性

**Comment by ishland** [comment]
Please provide logs.

**Comment by stoneStarRiver** [comment]
https://paste.ubuntu.com/p/j2fg6P7Y5G/
对吗

**Comment by ishland** [comment]
I'm not entirely sure what can be causing this due to the mod YSM being All Rights Reserved. 
Try reproduce with `use_optimized_entity_tracking` disabled.

**Comment by stoneStarRiver** [comment]
禁用`use_optimized_entity_tracking`没有解决问题.
不过这个问题不是必须解决的
