### ISSUE TITLE
VMP causes Carpet's `/player <name> spawn` to spawn player bots in wrong dimension.

### ISSUE THREAD

**Issue by ASchneider-GitHub** [RelativityMC/VMP-fabric#72]
**Describe the bug**
When using VMP and running the command `/player <name> spawn` in either the Nether or The End the bot that spawns will arrive in the Overworld, but will keep the coordinates of where you were standing in the non-Overworld dimension. See screenshots for a visual explanation. When VMP is disabled, the bots spawn in as expected. 

**To Reproduce**
Install latest release of VMP and Carpet, run command in non-Overworld dimension

**Expected behavior**
VMP should not interfere with the spawning of offline players through Carpet

**Screenshots**

**Nether - Command:**
![342048279-b596cbd3-c2b6-4a14-9980-b2d7dd67f231](https://github.com/user-attachments/assets/e0b09ace-5f04-4e80-9d82-e9569a522570)

**Nether - Result:**
![342048300-ccce7c59-2e97-4e3a-97c2-b028cce0252b](https://github.com/user-attachments/assets/b8958508-e1c5-4e6b-af3f-cbfdbccbccf5)

The End - Command:
![342048324-59bfc3af-e692-4209-ac81-8745f6150ac0](https://github.com/user-attachments/assets/cb5de71d-a030-40f5-ac04-920819a4effa)

**The End - Result:**
![342048336-0e241a2a-2c30-4c3b-9125-80c6bf0293e8](https://github.com/user-attachments/assets/1e77c637-1366-44f0-a379-d93d6ef232ec)

In another test, I found that the bot has metadata related to entering the nether at the specified coordinates stored, which would seem to indicate that they spawn in correctly and then are teleported to the Overworld at their Nether coordinates.

**Runtime info (please complete the following information):**
 - OS: Windows 10
 - Minecraft version: 1.21 
 - Mod version: `vmp-fabric-mc1.21-0.2.0+beta.7.163-all.jar` (https://modrinth.com/mod/vmp-fabric)
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Other mods**
`fabric-carpet-1.21-1.4.147+v240626.jar`

**Checklist**

 - [ x ] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. 
 - [ x ] I searched for similar open issues and could not find an existing bug report on this. 
    - [Abandoned Issue](https://github.com/RelativityMC/VMP-fabric/issues/67)

**Additional context**
Initially filed bug report with Carpet [here](https://github.com/gnembon/fabric-carpet/issues/1935) but was ultimately sent to this repo instead since it's VMP interfering with Carpet.

**Comment by ishland** [comment]
Should be fixed in 7e0b751166d7077b90d1c22cd3e70460adf2a67e
