### ISSUE TITLE
when server add the vmp it crash

### ISSUE THREAD

**Issue by blackvccat** [RelativityMC/VMP-fabric#74]
server crash when add the vmp

[crash.zip](https://github.com/user-attachments/files/16643727/crash.zip)
  
when  out of the vmp it work

**Comment by ishland** [comment]
Sinytra connector is not supported at the moment.

**Comment by blackvccat** [comment]
but I ues forge version vmp it can't work too

**Comment by ishland** [comment]
Then open an issue on the forge repository.
