### ISSUE TITLE
VMP Compat issues with an Hugh modpack. Without VMP it does work fine.

### ISSUE THREAD

**Issue by suerion** [RelativityMC/VMP-fabric#79]
**Describe the bug**
With VMP it crash the server with a lot of Mods (allways an other Mod after disabling)

**To Reproduce**
1. Add VMP on Modpack
2. Start Server
3. See logs after Crashing the server

after disabling mods, it will allways crash with an other mods...

**Expected behavior**
Server Start without Crash

**Runtime info (please complete the following information):**
 - OS: Windows Server 2019
 - Minecraft version: 1.21.1
 - Mod version: vmp-fabric-mc1.21.1-0.2.0+beta.7.169-all

**Crash reports / logs**
https://mclo.gs/S35ozfc

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

https://github.com/MrCrayfish/Framework/issues/30

**Comment by ishland** [comment]
Have you tried w/o vmp? Looks like connectivity is the one crashing.

**Comment by suerion** [comment]
Hey, had tried without connectivity and without vmp, 

When i start with connectivity and with vmp, it has an own issue, but  without connectivity, vmp let crash the different mods

https://mclo.gs/Fvcd9xI


Without connectivity and only vmp it does allways crash some mods like framework etc...

I could do restart my tests if you want for more different logs. The above one i had given to connectivity.

Had disabled 90% of my mods. To check whats the issue here.

**Comment by someaddons** [comment]
hi, author of connectivity here. This one is actually quite interesting, I'm marking all my mixins as "required:false" to allow it to skip on conflicts, but that seems to only work if you run mixin in debug mode for some reason (unlike forge, where it does skip as intended). 
Related bug report is here:
https://github.com/FabricMC/Mixin/issues/161
Gonna adapt my mixin to require 0 targets, so it no longer crashes it has the same intention as your mixin anyways

**Comment by suerion** [comment]
Hey @someaddons thanks again for your work :)

Will test it tomorow if it does work :)

**Comment by suerion** [comment]
Had no issues on this anymore.

Will close the issue :)
